WEF Application/WEF/WEF/Models/ErrorViewModel.cs
using System;

namespace WEF.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WEF Application/WEF/WEF/Models/GeneralEvents.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace WEF.Models
{
    public partial class GeneralEvents
    {
        [Display(Name = "Event ID")]
        public int? Id { get; set; }
        [Display(Name = "Log Level")]
        public string LevelDisplayName { get; set; }
        [Display(Name = "Log Name")]
        public string LogName { get; set; }
        [Display(Name = "Device Name")]
        public string MachineName { get; set; }
        [Display(Name = "Message")]
        public string Message { get; set; }
        [Display(Name = "Provider Name")]
        public string ProviderName { get; set; }
        [Display(Name = "Record ID")]
        public long? RecordId { get; set; }
        [Display(Name = "Task Display Name")]
        public string TaskDisplayName { get; set; }
        [Display(Name = "Time Created")]
        public DateTime? TimeCreated { get; set; }
    }
}

WEF Application/WEF/WEF/Controllers/EventsController.cs
using System;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WEF.Data;
using WEF.Models;

namespace WEF.Controllers
{
    [Microsoft.AspNetCore.Authorization.Authorize]
    public class EventsController : Controller
    {
        private readonly EventCollectionsContext _context;

        public EventsController(EventCollectionsContext context)
        {
            _context = context;
        }

        // GET: Events
        public async Task<IActionResult> Index(int? eventsID, string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            var viewModel = new EventsIndexData
            {
                Events = await _context.GeneralEvents
                  .AsNoTracking()
                  .OrderBy(i => i.Id)
                  .ToListAsync().ConfigureAwait(true)
            };
            if (eventsID != null)
            {
                ViewData["DevicesID"] = eventsID.Value;
                GeneralEvents eventModels = viewModel.Events.Where(i => i.Id == eventsID.Value).Single();
            }

            ViewData["CurrentSort"] = sortOrder;
            ViewData["Id"] = sortOrder;
            ViewData["LevelDisplayNameParam"] = String.IsNullOrEmpty(sortOrder) ? "leveldisplayname_desc" : "";
            ViewData["LogNameParam"] = String.IsNullOrEmpty(sortOrder) ? "logname_desc" : "";
            ViewData["MachineNameParam"] = String.IsNullOrEmpty(sortOrder) ? "machinename_desc" : "";
            ViewData["MessageParam"] = String.IsNullOrEmpty(sortOrder) ? "message_desc" : "";
            ViewData["ProviderNameParam"] = String.IsNullOrEmpty(sortOrder) ? "providername_desc" : "";
            ViewData["RecordIdParam"] = String.IsNullOrEmpty(sortOrder) ? "recordid_desc" : "";
            ViewData["TaskDisplayNameParam"] = String.IsNullOrEmpty(sortOrder) ? "taskdisplayname_desc" : "";
            ViewData["TimeCreated"] = sortOrder == "Date" ? "date_desc" : "Date";
            
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;

            var events = from e in _context.GeneralEvents
                          select e;
            if (!string.IsNullOrEmpty(searchString))
            {
                events = events.Where(e => e.Message.Contains(searchString) || e.LevelDisplayName.Contains(searchString) || e.LogName.Contains(searchString) || e.MachineName.Contains(searchString) || e.ProviderName.Contains(searchString) || e.TaskDisplayName.Contains(searchString) || e.TimeCreated.ToString().Contains(searchString) || e.RecordId.ToString().Contains(searchString) || e.Id.ToString().Contains(searchString));
            }
            switch (sortOrder)
            {
                case "leveldisplayname_desc":
                    events = events.OrderByDescending(e => e.LevelDisplayName);
                    break;
                case "logname_desc":
                    events = events.OrderByDescending(e => e.LogName);
                    break;
                case "machinename_desc":
                    events = events.OrderByDescending(e => e.MachineName);
                    break;
                case "message_desc":
                    events = events.OrderByDescending(e => e.Message);
                    break;
                case "providername_desc":
                    events = events.OrderByDescending(e => e.ProviderName);
                    break;
                case "recordid_desc":
                    events = events.OrderByDescending(e => e.RecordId);
                    break;
                case "taskdisplayname_desc":
                    events = events.OrderByDescending(e => e.TaskDisplayName);
                    break;
                case "Date":
                    events = events.OrderBy(e => e.TimeCreated);
                    break;
                case "date_desc":
                    events = events.OrderByDescending(e => e.TimeCreated);
                    break;
                default:
                    events = events.OrderByDescending(e => e.Id);
                    break;
            }       
            int pageSize = 10;
            return View(await PaginatedListCollection<GeneralEvents>.CreateAsync(events.AsNoTracking(), pageNumber ?? 1, pageSize));
        }


        // GET: Events/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.GeneralEvents
                .FirstOrDefaultAsync(e => e.Id == id);
            if (events == null)
            {
                return NotFound();
            }

            return View(events);
        }

        // GET: Events/Delete/5
        public async Task<IActionResult> Delete(int? id, bool? saveChangesError = false)
        {
            if (id == null)
            {
                return NotFound();
            }

            var events = await _context.GeneralEvents
                .AsNoTracking()
                .FirstOrDefaultAsync(e => e.Id == id);
            if (events == null)
            {
                return NotFound();
            }
            if (saveChangesError.GetValueOrDefault())
            {
                ViewData["ErrorMessage"] =
                    "Delete failed. Try again, and if the problem persists " +
                    "see your system administrator.";
            }

            return View(events);
        }

        // POST: Events/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var events = await _context.GeneralEvents.FindAsync(id);
            if (events == null)
            {
                return RedirectToAction(nameof(Index));
            }

            try
            {
                _context.GeneralEvents.Remove(events);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                Debug.WriteLine(ex.Message);
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }

        private bool EventsExists(int id)
        {
            return _context.GeneralEvents.Any(e => e.Id == id);
        }
    }
}

WEF Application/WEF/WEF/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WEF.Models;

namespace WEF.Controllers
{
    [Microsoft.AspNetCore.Authorization.AllowAnonymous]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WEF Application/WEF/WEF/Views/Events/Delete.cshtml
@model WEF.Models.GeneralEvents

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Events</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LevelDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LevelDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LogName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LogName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MachineName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MachineName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProviderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecordId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecordId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WEF Application/WEF/WEF/Views/Events/Details.cshtml
@model WEF.Models.GeneralEvents

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Events</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LevelDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LevelDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LogName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LogName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MachineName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MachineName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProviderName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProviderName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RecordId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RecordId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TaskDisplayName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TaskDisplayName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimeCreated)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimeCreated)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

WEF Application/WEF/WEF/Views/Events/Index.cshtml
@model PaginatedListCollection<WEF.Models.GeneralEvents>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-controller="Events" asp-action="Index" method="get">
    <p>
        <input style="text-align:left" type="text" name="SearchString" class="btn btn-dark" value="@ViewData[" CurrentFilter"]" />
        <input type="submit" value="Search" class="btn btn-dark" />
        <a asp-action="Index" style="color:#A6192E">Back to Full List</a>
    </p>
</form>

<div>
<table class="table-responsive table-striped table-bordered" border="1" cellspacing="8" title="Event Logs" cellpadding="8">
    <thead>
        <tr>
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" Id"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Event Id</a>
            </th>
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" LevelDisplayNameParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">LevelDisplayName</a>
            </th>
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" LogNameParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">LogName</a>
            </th>
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" MachineNameParam"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">MachineName</a>
            </th>
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" Message"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Message</a>
            </th>
            <!-- Uncomment these lines if you wish to display all available event information in the SQL table. This info will currently only be displayed after clicking the Details button
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@@ViewData[" ProviderNameParam"]" asp-route-currentFilter="@@ViewData["CurrentFilter"]">ProviderName</a>
            </th>
                <th style="color:#A6192E">
                    <a asp-action="Index" asp-route-sortOrder="@@ViewData[" RecordIdParam"]" asp-route-currentFilter="@@ViewData["CurrentFilter"]">RecordId</a>
                </th>
                <th style="color:#A6192E">
                    <a asp-action="Index" asp-route-sortOrder="@@ViewData[" TaskDisplayNameParam"]" asp-route-currentFilter="@@ViewData["CurrentFilter"]">TaskDisplayName</a>
                </th>
            -->
            <th style="color:#A6192E">
                <a asp-action="Index" asp-route-sortOrder="@ViewData[" TimeCreated"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">TimeCreated</a>
            </th>
            <th style="color:#A6192E">
                Options
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LevelDisplayName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LogName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MachineName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Message)
                </td>
                <!-- I removed these lines for a more readable table. Use the details button to view this information
                <td>
                    @@Html.DisplayFor(modelItem => item.ProviderName)
                </td>
                <td>
                    @@Html.DisplayFor(modelItem => item.RecordId)
                </td>
                <td>
                    @@Html.DisplayFor(modelItem => item.TaskDisplayName)
                </td>
                -->
                <td>
                    @Html.DisplayFor(modelItem => item.TimeCreated)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id" style="color:#A6192E">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id" style="color:#A6192E">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
</div>


<div style="float:right">
    <br />
    <p><strong>Page @(Model.PageIndex) of @(Model.TotalPages)</strong></p>
    <p><strong>@(Model.Count) Devices Displayed</strong></p>
</div>
<p>
    <div>
        <hr />
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@((Model.PageIndex - Model.PageIndex) + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @prevDisabled">
            First Page
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 2)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @prevDisabled">
            <<
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @prevDisabled">
            Previous
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @nextDisabled">
            Next
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + 2)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @nextDisabled">
            >>
        </a>
        <a asp-action="Index"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(Model.PageIndex + (Model.TotalPages - Model.PageIndex))"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="btn btn-dark @nextDisabled">
            Last Page
        </a>
    </div>
</p>

WEF Application/WEF/WEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<style>
    .codebox {
        border: 1px solid black;
        background-color: #FFFFFF;
        width: 100%;
        overflow: auto;
        padding: 10px;
    }

    .codebox code {
        font-size: 0.9em;
        color: black
    }
</style>

<div class="text-left">
    <center><h1 style="color: #FFFFFF" class="display-4"><strong>Windows Event Forwarding Application</strong></h1></center><br />
    <p>
        ASP.NET Core 3.1 web application that is used to investigate log files that have a high indication of compromise. These logs were collected from all devices in the environment. Below is a list of Events collected.<br />
        <br />
        <strong style="color: #FFFFFF">Domain Computer Events: </strong><br />
        <ul>
            <li><strong>1102:</strong> Event Log Cleared</li>
            <li><strong>4732:</strong> User added to an Administrators group</li>
            <li><strong>4733:</strong> User removed from an Administrators group</li>
            <li><strong>4720:</strong> Local User account created</li>
            <li><strong>4726:</strong> Local User account deleted</li>
            <li><strong>7045:</strong> New Service Installed</li>
        </ul>
        <br />
        <strong style="color: #FFFFFF">Domain Controller Events: </strong><br />
        <ul>
            <li><strong>1102:</strong> Event Log Cleared</li>
            <li><strong>4732:</strong> User added to an Administrators group</li>
            <li><strong>4733:</strong> User removed from an Administrators group</li>
            <li><strong>4720:</strong> Local User account created</li>
            <li><strong>4726:</strong> Local User account deleted</li>
            <li><strong>7045:</strong> New Service Installed</li>
            <li><strong>4756:</strong> Domain User Added to a Universal Security Group</li>
            <li><strong>4757:</strong> Domain User Removed from a Universal Security Group</li>
            <li><strong>4728:</strong> Domain User Added to Global Security Group</li>
            <li><strong>4729:</strong> Domain User Removed Global Security Group</li>
            <li><strong>4649:</strong> Replay Attack Detected</li>
            <li><strong>4723:</strong> User Attempted to Change Password</li>
            <li><strong>4724:</strong> Admin Attempted to change someone else's password</li>
        </ul>
    </p>
    <p>
        This web application is built to work with the set up of Windows Event Forwarding where the log files are collected and sent to a SQL database.
        Directions to configure the SQL database, Task Scheduler Alerts, and the Windows Event Forwarding Configuration in an environment can be found <a href="https://github.com/tobor88/OsbornePro-The-Blue-Team-Security-Package"><strong>HERE</strong></a>.
    </p>

    <h4 style="color: #FFFFFF"><strong>Installed and Required Packages</strong></h4>
    <p>
        Issue the below commands in Visual Studio 2019 Package Manager Console to install required packages.
        <div class="codebox">
            <code>
                PS> Install-Package Microsoft.EntityFrameworkCore.SqlServer<br />
                PS> Install-Package Microsoft.EntityFrameworkCore.InMemory<br />
                PS> Install-Package Azure.Identity<br />
                # OR<br />
                # If you need to use the dotnet commands you can cd into the second WEF directory and issue the below commands.<br />
                PS> dotnet add package Microsoft.EntityFrameworkCore.SqlServer<br />
                PS> dotnet add package Microsoft.EntityFrameworkCore.InMemory<br />
                PS> dotnet add package Azure.Identity<br />
            </code>
        </div>
    </p>
    <p>
        <h2 style="color: #FFFFFF"><strong>Summary</strong></h2>
        The purpose of this web application is to easily investigate any email alerts received that indicate a possible compromise.
        This server has Windows Event Forwarding (WEF), configured in a "source collector" set up. This means that the clients in the environment initiate connections to the server before sending logs.
        When one of the above event ID's I defined above occur on any of the devices, the event info is forwarded to the WEF source collector server using WinRM over HTTPS. 
        Once an hour the collected event logs are imported into a SQL database. Any newly discovered events that indciate possible compromise trigger an email alert which sends to the IT Administrators.
        This application can be used to search that SQL database. The SQL database is useful because searching a SQL database is 100x faster than parsing the Windows Event Logs through XML. 
        It also stores more criticial events for a longer period of time then the events would exists inside Event Viewer. This is because when Event Viewer logs reach a certain size, old logs are removed to make room for new ones.<br />
        <br />
        <h4 style="color: #FFFFFF"><strong>Authentication</strong></h4>
        After a user with permission to access the device database authenticates their identity, they will be taken a new site extension with the ability to search and view events collected by WEF.
        Authentication is handled through Azure AD integration. Members in a group defined by IT have the ability to access the full functionality of the web application after signing in.
        When someone signs in that does not have access to the database they receive an Error Code 500 and they will be denied access.
        Unauthorized users will not be able to access the SQL database or any of it’s features.<br />
        <br />
        <h4 style="color: #FFFFFF"><strong>Data Functions</strong></h4>
        The columns in the database table can be organized by ascending or descending order. This is done by clicking the blue link column header.
        The search will parse the database by searching for the specified term in all of the columns. Other parameters can be added if ever requested.
        There are presently 10 items displayed per page. This can also be changed if ever requested. The same features are available in the rentals area.
        Any of the entries can be deleted in case an event is taking up space. Events can also be shown in a detailed view.<br />
        <br />
        <h4 style="color: #FFFFFF"><strong>Logging</strong></h4>
        Any and all changes are currently logged through the web platform, the operating system, and the cloud. Custom log messages will be added in a future version to further simplify troubleshooting.
        Error handling has been configured. Please report any errors that do not respond as expected.<br />
        <br />
        <h4 style="color: #FFFFFF"><strong>Platform Testing</strong></h4>
        Protection against SQL injections and CSRF have been implemented. Penetration testing has been performed to ensure the security of the application. There are no presently discovered vulnerabilities.
    </p>
</div>

WEF Application/WEF/WEF/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WEF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
 <style>
     body {
         background-color: #071D49;
         color: #A7A8AA
     }
 </style>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">
                    <img src="~/images/osborneprologo.png" alt="WEF Application" height="30" width="130" asp-area="" asp-page="/Index">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Events" asp-action="Index">Events</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer bg-dark navbar-dark text-light">
        <div class="container">
            &copy; 2020 - OsbornePro - WEF - <a asp-area="" asp-controller="Events" asp-action="Index">View Events Database</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>